{% set name = "jedi" %}
{% set version = "0.10.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: jedu-v{{ version }}.tar.gz
  url: https://github.com/davidhalter/jedi/archive/v{{ version }}.tar.gz
  sha256: d6a7344df9c80562c3f62199278004ccc7c5889be9f1a6aa5abde117ec085123

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - jedi

about:
  home: https://github.com/davidhalter/jedi/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: An autocompletion tool for Python that can be used for text editors.
  description: |
    Jedi is a static analysis tool for Python that can be used in IDEs/editors.
    Its historic focus is autocompletion, but does static analysis for now as
    well. Jedi is fast and is very well tested. It understands Python on a
    deeper level than all other static analysis frameworks for Python.
  dev_url: https://github.com/davidhalter/jedi/
  doc_url: http://jedi.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - goanpeca
    - asmeurer
