{% set name = "jedi" %}
{% set version = "0.12.0" %}
{% set sha256 = "1972f694c6bc66a2fac8718299e2ab73011d653a6d8059790c3476d2353b99ad" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    # the PyPI package pins to 0.1.1 but appears to work with 0.1.*
    # see https://github.com/davidhalter/jedi/commit/fc039773
    - parso >=0.1.0,<0.2

test:
  imports:
    - jedi

about:
  home: https://github.com/davidhalter/jedi/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: An autocompletion tool for Python that can be used for text editors.
  description: |
    Jedi is a static analysis tool for Python that can be used in IDEs/editors.
    Its historic focus is autocompletion, but does static analysis for now as
    well. Jedi is fast and is very well tested. It understands Python on a
    deeper level than all other static analysis frameworks for Python.
  dev_url: https://github.com/davidhalter/jedi/
  doc_url: http://jedi.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - goanpeca
    - asmeurer
    - nehaljwani
