travis:
  secure:
    BINSTAR_TOKEN: XJESdd4R3tyIBjVUXKeDlPkjaf3VdSpLrrNfnNvs6ltYp+AAbfvVJWGAwCLea1lds8K5Y6GVdW1u2/6wToRWQkPF6ry8bx2t97vPRHEwIwmPAwf46Cpt+jHwbPrlxo+kjoW8/TE3DjfzQi4zm8qpJbz8i2L5MLRSYlKAlkzCawvaSj09UEzjQBEPdfdGbn4SL9GhxiDFbYhVo+swFkyOAx9kPi/Q8FlpaSCdHOxX/4bijYgiFeFW6fmO8GgF8TRRm/C1My05K3D7FgOhgGllMVAgriwTx1kad4JDR/7kHFzb5HMcUNhdyRXqA/muV6VwHYSuoNCaDVrSOt1aNF6Z1QmIMLIGsHhiayLCk0wREYOcYYNla0Ne7dNWjBTqHjwNeF3DEoyfuXZX4+WITBG8N89rYkPRjGlRSejuDDE4Ua9aDBxe3V3zJz2NdArKnrpxYm9qajxiTtJcOh+Me0RMKmxD0PWWIz9pJ3YNgAgeiZ5bfkDjVeQIE3UFiNPH1r76NShHgRSoge9FyIstPP7gcz/h6qn5nREfdA0O4OqZkI3cxIayyGRdGmASjyIgXjy02rPd98nQBwedd021u+gWOy0J4JNcexKqcek3l+4h3doZkzUdzDw4ukJeJvMV4y27NGFiCUNkjHyYy9aMLCoklKqaU/z3O0eTwHzJ3NBXe4Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
